# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(914, 637)
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 171, 391))
        self.treeWidget.setObjectName("treeWidget")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 440, 891, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 380, 171, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(190, 340, 701, 91))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 391, 41))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 30, 101, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(550, 30, 101, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 350, 151, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(670, 10, 231, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 131, 231))
        self.label_2.setMouseTracking(True)
        self.label_2.setAcceptDrops(True)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 270, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 20, 231, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 30, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 30, 101, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 121, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(190, 130, 451, 201))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(330, 30, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 30, 101, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_9.setGeometry(QtCore.QRect(40, 30, 101, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 90, 101, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(430, 20, 231, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 30, 101, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_12.setGeometry(QtCore.QRect(120, 30, 101, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 121, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.reboot)
        self.pushButton_2.clicked.connect(Form.screencap)
        self.pushButton_3.clicked.connect(Form.log)
        self.pushButton_4.clicked.connect(Form.reload)
        self.pushButton_5.clicked.connect(Form.choose)
        self.pushButton_6.clicked.connect(Form.install)
        self.pushButton_7.clicked.connect(Form.stoplog)
        self.pushButton_8.clicked.connect(Form.lock)
        self.pushButton_9.clicked.connect(Form.unlock)
        self.pushButton_10.clicked.connect(Form.ip)
        self.pushButton_11.clicked.connect(Form.screenrecord)
        self.pushButton_12.clicked.connect(Form.stoprecord)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "adbTool by xjming"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "Devices"))
        self.pushButton_4.setText(_translate("Form", "刷新"))
        self.groupBox.setTitle(_translate("Form", "程序安装"))
        self.pushButton_5.setText(_translate("Form", "选择"))
        self.pushButton_6.setText(_translate("Form", "安装"))
        self.groupBox_2.setTitle(_translate("Form", "截图"))
        self.pushButton_2.setText(_translate("Form", "截图"))
        self.groupBox_3.setTitle(_translate("Form", "记录日志"))
        self.pushButton_3.setText(_translate("Form", "开始"))
        self.pushButton_7.setText(_translate("Form", "停止"))
        self.groupBox_4.setTitle(_translate("Form", "手机操作"))
        self.pushButton.setText(_translate("Form", "重启"))
        self.pushButton_8.setText(_translate("Form", "锁屏"))
        self.pushButton_9.setText(_translate("Form", "解锁"))
        self.pushButton_10.setText(_translate("Form", "手机IP"))
        self.groupBox_5.setTitle(_translate("Form", "屏幕录制"))
        self.pushButton_11.setText(_translate("Form", "开始"))
        self.pushButton_12.setText(_translate("Form", "结束"))

